[package]
name = "server"
version = "0.1.0"
authors = ["JScearcy <jacobscearcy@gmail.com>"]

[dependencies]
iron = "*"
router = "*"
rustc-serialize = "*"
staticfile = "*"
persistent = "*"
rusqlite = "*"
time = "*"

[dependencies.mount]

git = "https://github.com/iron/mount.git"